services:
  postgres:
    image: postgres
    volumes:
      - localdb:/app/node/server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=davi
      - POSTGRES_DB=ecommecer
    ports:
      - "5432:5432"
volumes:
  localdb: